### ISSUE TITLE
cal_exon_intron_length.py

### ISSUE THREAD

**Issue by frylhc** [lyijin/pdae_dna_meth#2]
Hi Dr. Liew, when I am trying to use your python script cal_exon_intron_length.py, I came up with the following error messages: 
`Traceback (most recent call last):
  File "/home/data/gmb46/pdai_dna_meth_master/descriptive/genomic_context/calc_exon_intron_lengths.py", line 22,                  in <module>
    scaffold_gff3 = parse_gff3.parse_gff3(args.genome_gff3, 'exon')
  File "/home/data/gmb46/pdai_dna_meth_master/descriptive/genomic_context/parse_gff3.py", line 201, in parse_gff3
    gff_details[seqid][gene_id].add_mRNA(mRNA_id, coords)
UnboundLocalError: local variable 'gene_id' referenced before assignment
`
  I am new in bioinformatics, and I presume that the nineth column of my gff3 files might have caused the error, which might be different from yours. I have seen a line in your script
`RNA-1;1.gff:1000131     maker   five_prime_UTR  1968    1999    .    +       .       ID=maker-1000131-exonerate...,` and here is an example of my gff3 file: `Chr1    ky2019  mRNA    3120    4642    .       -       .       Parent=KY2019:KY.Chr1.1;Name=KY.Chr1.1.v1.SL12-1;ID=KY2019:KY.Chr1.1.v1.SL12-1;Target=KY.Chr1.1.v1.SL12-1 1 1042;Note=ORF:[23..688/1042]%3B%20Fgf11/12/13/14%20%28fibroblast%20growth%20factorf%2011/12/13/14%29%3BHuman%20Homolog:[FGF13%20%28HGNC:3670%2C%20fibroblast%20growth%20factor%2013%29]
Chr1    ky2019  exon    4621    4642    .       -       .       Parent=KY2019:KY.Chr1.1.v1.SL12-1;Target=KY.Chr1.1.v1.SL12-1 1 22
`
I don't understand what ID means here, does it mean the name of the gene, corresponding transcript or the ID number of exons in one transcript?

**Comment by lyijin** [comment]
right, i'll answer in reverse.

ID is a unique identifier for each feature. see http://gmod.org/wiki/GFF3, scroll down to "protein-coding genes" for a complete example of a gene's GFF3. basically, there should not be two identical IDs in your file; everytime you see a "ID=", the value should be unique. scripts that parse GFF3s might fail/crash if your GFF3 contains IDs that are shared across lines.

from experience, GFF3 files are REALLY non-standard, so i'm afraid i can't really help you when it breaks on your files. often, the script `parse_gff3.py` (*) throws an error that is hard to understand. i can only guarantee it working on the genomes we produced (and will help debug if errors are produced while using these GFF3s)... but not other gff3 files, sorry.

that said, i have two guesses

1. perhaps your GFF3 file isn't sorted. my script assumes that the gene line would appear first, before the subfeatures under the gene (5' UTR, exon, 3' UTR...).
2. i also assumed that mRNA are labelled as "mRNA", not "transcripts".

the script should work even when ID is in the middle of the ninth column (the attributes column). the script should also work even when your exons do not have IDs, i only need IDs for the gene and for the mRNA (lines 206-216 of `parse_gff3.py`).

are you interested in getting the mean lengths of exon 1, 2, 3, ... and intron 1, 2, 3, ...; or are you interested in calculating mean exon/intron lengths from all gene models? the former needs a script; the latter can be done on the command line (which avoids the crash). i can show you how to do the latter if that's all you need.

*: i'm glad you found the `parse_gff3.py` script, but just to be precise, it's linked here: https://github.com/lyijin/common/blob/master/parse_gff3.py

**Comment by lyijin** [comment]
because my script doesn't assume that exons have valid IDs, it actually parses the coordinates of the exons belonging to the mRNA, sorts them in order, then numbers them in order of exon 1, exon 2, ...

once we get exonic coordinates, e.g. (10, 100), (200, 300), (400, 500), the intronic coordinates can be inferred as the gaps between the end of one exon and the start of the next one, i.e. (101, 199), (301, 399).

**Comment by frylhc** [comment]
Thanks a lot for your advice. I have been busying solving other problems in the past two days,  so I did not respond. I am trying to read the script line by line now, hoping will figure it out. By the way, I have read your artical "Intergenerational epigenetic inheritance in reef-building corals", your work have inspired me a lot, especially on data analyzing. Again, thank you for your advice.
